# Файл: sonarqube_scan.yml

stages:
  - test

sonarqube_scan:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_TOKEN: "your_sonar_token"
    SONAR_HOST_URL: "https://your_sonarqube_server"
  script:
    - sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.sources=. -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL
